### ISSUE TITLE
Heroku fail

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG5/News-Project#22]
![image](https://user-images.githubusercontent.com/28482442/43548006-9680c752-95e5-11e8-9be6-8525647a232c.png)

**Comment by Asmaa-ezz** [comment]
we solve the all error 
Try to enter this [link](https://news-project2.herokuapp.com/) 
and the image sure to work

<img src="http://www13.0zz0.com/2018/08/02/10/483232476.png">
