### ISSUE TITLE
What to test for

### ISSUE THREAD

**Issue by NoureldeanSaed** [FACG5/News-Project#23]
https://github.com/FACG5/News-Project/blob/396f873494fabb9397e69fd7367b3716efc83645/testing/test.js#L14
https://github.com/FACG5/News-Project/blob/396f873494fabb9397e69fd7367b3716efc83645/testing/test.js#L8

These two lines test for the same thing

**Comment by Asmaa-ezz** [comment]
Thanks of issues
I know the test same work but not sure it because we learn this in workshop
